[basic info]
testsiteurl=https://gosystemrs.fasttax.com/Default.asp

[pytest]
addopts= --browser-chrome --headed --slowmo=2000

[locators]
#Gosystem - LoginPage locators

LoginID_CSS=#loginId
Firm_CSS=#firm
Location_CSS=#location
Password_CSS=#password
login_CSS=button.login-button



#Gosystem - Home page locators
iframeid_ID=ATopMenuFrame
returnsoptn_ID=topLReturns
logout_CSS=.logout-button
#create Returns
createReturn_ID=btnCreate
iframe_mainMenu_ID=main
Account_XPATH=//*[@id="account"]/input
Year_NAME=comboxInput

#Create Return Page Locator
returns_id=#Returns
create_return_btn=#create-return-btn
select_year=[placeholder="Select Year"]
Select Type=[placeholder="Select Type"]

#Taxpayer Information locators

fname_css=#Taxpayer-firstName-field input
lname_css=#Taxpayer-lastName-field input
checkbox_css=#control
create_btn=button[type="submit"]

#Open return popup window locator
single_user=#single-user input
continue_btn=#submit-btn

#get Locator from h1 tag
locator_id=#locator-header

#TaxReturn Information Page locators
general_info_txt= General Information
basic_return_info= Basic Return Information
Taxpayer_info= Taxpayer Information
#Selecting Filling state
Filling_state=#select-11

#Entering SSN, DOB etc.

SSN=#otw_textbox_5
DOB=#otw_textbox_24

#ADDRESS locators

Address1=#otw_textbox_11
Address2=#otw_textbox_13
Apartment=#otw_textbox_12

city=#otw_textbox_14
county=#otw_textbox_17
state=#select-21
zip=#otw_textbox_16


compute=#otw-toolbar-item-left0
Full_recompute=#otw-toolbar-menu-left0 > saf-menu-item:nth-child(1)
Close_btn=[aria-label="Close"]
